# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        language: system
        entry: black
        types: [python]
    -   id: pycln
        name: pycln
        description: "A formatter for finding and removing unused import statements."
        entry: pycln
        args: [ "--all" ]
        language: python
        language_version: python3
        types: [python]
    -   id: isort
        name: isort (python)
        entry: isort
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        additional_dependencies: [ flake8-bugbear, flake8-noqa, dlint ]
        language: python
        types: [ python ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        -   id: check-ast
        -   id: check-docstring-first
        -   id: check-merge-conflict
        -   id: check-toml
        -   id: end-of-file-fixer
            types: [python]
        -   id: requirements-txt-fixer
        -   id: trailing-whitespace
            types: [python]
